---
title: "Nematode Composition"
author: "Wei, C.-L., Liao, J.-X."
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

# Reguired package
```{r}
library(nema)
library(reshape2)
library(plyr)
library(vegan)
library(viridis)
library(ggdendro)
library(ggplot2)
```

# ggplot them setting
```{r}
large <- theme(legend.title = element_text(size=15),
        legend.text = element_text(size=15),
        axis.title = element_text(size=15),
        axis.text = element_text(size=15),
        strip.text = element_text(size=15))

rotate <- theme(axis.text.x = element_text(angle = 30, hjust=0.5))

no_strip <- theme(strip.background = element_rect(colour=NA, fill=NA),
                  strip.text = element_text(colour=NA))
```

# Preparing nematode and environmental data
```{r}
b <- acast(nema_abund, Cruise+Station+Deployment+Tube+Subcore~Genus+Species, fill=0)
e <- ldply(strsplit(row.names(b), split="_"))
e <- cbind(with(e, paste(V1, V2, sep="_")), e[,-1:-2])
names(e) <- c("Cruise", "Station", "Deployment", "Tube", "Subcore")
id1 <- with(e, paste(Cruise, Station, Deployment))
id2 <- with(nema_cruise, paste(Cruise, Station, Deployment))
e <- cbind(e, nema_cruise[match(id1, id2), -3:-5])
```

# Cluster Analysis and 
```{r, fig.width=8, fig.height=4}
# Hierarchical Clustering based on square root transformed abundance data 
# Agglomeration used group average (= UPGMA) method
d <- vegdist(b^0.25)
hc <- hclust(d, method="average")
hc$labels <- with(e, paste(gsub("OR1_", "", Cruise), Station, sep="-"))

# Convert dendrogram to ggplot style
dhc <- as.dendrogram(hc)
ghc    <- dendro_data(dhc, type="rectangle") 

# Merge env data to dendrogram label data frame
ord <- match(label(ghc)$label, with(e, paste(gsub("OR1_", "", Cruise), Station, sep="-")))
ghc[["labels"]]   <- cbind(ghc[["labels"]], e[ord,])

ggdendrogram(hc, rotate = FALSE)+
  geom_point(data=label(ghc), aes(x, y, fill=Habitat), size=4, pch=21, colour=gray(0, 0.2))+
  scale_fill_viridis(discrete = TRUE)
```

# Nonmetric Multidimensional Scaling
```{r, fig.width=8, fig.height=4}
md <- metaMDS(vegdist(b^0.25))
stress <- paste("Stress = ", deparse(round(md$stress,2)))

# Merge MDS to environmental data frame
ggplot(data=cbind(md$points, e), aes(x=MDS1, y=MDS2, fill=Habitat, colour=Habitat))+
  geom_point(pch=21, alpha=0.8, size=5, colour=gray(0, 0.2))+
  stat_ellipse(type="norm")+
  annotate("text", x=-0.45, y=-0.4, label=stress, size=5) +
  scale_fill_viridis(discrete = TRUE)+
  scale_color_viridis(discrete = TRUE)+
  theme_bw() %+replace% large
```

